# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name_plural': 'Animals'},
        ),
        migrations.AddField(
            model_name='animals',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animals',
            name='color',
            field=models.CharField(choices=[('none', 'Without color'), ('green', 'Green'), ('white', 'White')], default='none', max_length=44),
        ),
        migrations.AddField(
            model_name='animals',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='animals',
            name='owner',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='animals',
            name='weight',
            field=models.IntegerField(default=30),
        ),
    ]
