# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_auto_20171129_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={},
        ),
    ]
