# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_auto_20171129_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name_plural': 'Owners'},
        ),
    ]
